import "@mantine/core/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { ColorSchemeScript } from "@mantine/core";
import React from "react";
import { AuthStateChanged } from "@/app/shared/subscribers/AuthStateChanged";
import { Providers } from "./shared/providers/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>;

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="en" className={"h-full"}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={"h-full"}>
        <Providers>
          <div>navbar</div>
          <div
            className={
              "h-full max-w-screen-xl mx-auto flex items-center justify-center"
            }
          >
            {children}
            {modal}
          </div>
          <AuthStateChanged />
        </Providers>
      </body>
    </html>
  );
}
